directory_pcd: "/home/cjs/data/KITTI/data_odometry_velodyne/dataset/sequences/00/velodyne"
directory_image: "/home/cjs/data/KITTI/data_odometry_gray/dataset/sequences/00/image_0"
path_odom: "/home/cjs/data/KITTI/data_odometry_poses/dataset/poses/00.txt"
path_calib: "/home/cjs/data/KITTI/data_odometry_calib/dataset/sequences/00/calib.txt"
directory_combined_pcd: "/home/cjs/data/output/com_pcd_C_250/"

directory_output_com: "/home/cjs/data/output/com_pcd_"
directory_output_pro: "/root/data/output/normal_projection_KITTI/"